export const imageMap = {
    'Do': require('../assets/tonalidades/Do.png'),
    'Fa': require('../assets/tonalidades/Fa.png'),
    'Fa#': require('../assets/tonalidades/FaSOS.png'),
    'La': require('../assets/tonalidades/La.png'),
    'Lab': require('../assets/tonalidades/Lab.png'),
    'Mi': require('../assets/tonalidades/Mi.png'),
    'Mib': require('../assets/tonalidades/Mib.png'),
    'Re': require('../assets/tonalidades/Re.png'),
    'Reb': require('../assets/tonalidades/Reb.png'),
    'Si': require('../assets/tonalidades/Si.png'),
    'Sib': require('../assets/tonalidades/Sib.png'),
    'Sol': require('../assets/tonalidades/Sol.png'),
    'Solb': require('../assets/tonalidades/Solb.png'),

    'C': require('../assets/tonalidades/Do.png'),
    'F': require('../assets/tonalidades/Fa.png'),
    'F#': require('../assets/tonalidades/FaSOS.png'),
    'A': require('../assets/tonalidades/La.png'),
    'Ab': require('../assets/tonalidades/Lab.png'),
    'E': require('../assets/tonalidades/Mi.png'),
    'Eb': require('../assets/tonalidades/Mib.png'),
    'D': require('../assets/tonalidades/Re.png'),
    'Db': require('../assets/tonalidades/Reb.png'),
    'B': require('../assets/tonalidades/Si.png'),
    'Bb': require('../assets/tonalidades/Sib.png'),
    'G': require('../assets/tonalidades/Sol.png'),
    'Gb': require('../assets/tonalidades/Solb.png'),
};