export const notesMayor = [
    {
        firstInterval: '1',
        firstNote: 'C3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '2m',
        firstNote: 'Db3',
        secondInterval: '1+',
        secondNote: 'C#3',
    },
    {
        firstInterval: '2M',
        firstNote: 'D3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '3m',
        firstNote: 'Eb3',
        secondInterval: '2+',
        secondNote: 'D#3',
    },
    {
        firstInterval: '3M',
        firstNote: 'E3',
        secondInterval: '4-',
        secondNote: 'Fb3',
    },
    {
        firstInterval: '4J',
        firstNote: 'F3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '4+',
        firstNote: 'F#3',
        secondInterval: '5-',
        secondNote: 'Gb3',
    },
    {
        firstInterval: '5J',
        firstNote: 'G3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '6m',
        firstNote: 'Ab3',
        secondInterval: '5+',
        secondNote: 'G#3',
    },
    {
        firstInterval: '6M',
        firstNote: 'A3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '7m',
        firstNote: 'Bb3',
        secondInterval: '6+',
        secondNote: 'A#3',
    },
    {
        firstInterval: '7M',
        firstNote: 'B3',
        secondInterval: '1-',
        secondNote: 'Cb4',
    },
    {
        firstInterval: '1',
        firstNote: 'C4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '2m',
        firstNote: 'Db4',
        secondInterval: '1+',
        secondNote: 'C#4',
    },
    {
        firstInterval: '2M',
        firstNote: 'D4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '3m',
        firstNote: 'Eb4',
        secondInterval: '2+',
        secondNote: 'D#4',
    },
    {
        firstInterval: '3M',
        firstNote: 'E4',
        secondInterval: '4-',
        secondNote: 'Fb4',
    },
    {
        firstInterval: '4J',
        firstNote: 'F4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '4+',
        firstNote: 'F#4',
        secondInterval: '5-',
        secondNote: 'Gb4',
    },
    {
        firstInterval: '5J',
        firstNote: 'G4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '6m',
        firstNote: 'Ab4',
        secondInterval: '5+',
        secondNote: 'G#4',
    },
    {
        firstInterval: '6M',
        firstNote: 'A4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '7m',
        firstNote: 'Bb4',
        secondInterval: '6+',
        secondNote: 'A#4',
    },
    {
        firstInterval: '7M',
        firstNote: 'B4',
        secondInterval: '8-',
        secondNote: 'Cb5',
    },
    {
        firstInterval: '8J',
        firstNote: 'C5',
        secondInterval: '7+',
        secondNote: 'B#4',
    },
    {
        firstInterval: '9m',
        firstNote: 'Db5',
        secondInterval: '8+',
        secondNote: 'C#5',
    },
    {
        firstInterval: '9M',
        firstNote: 'D5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '10m',
        firstNote: 'Eb5',
        secondInterval: '9+',
        secondNote: 'D#5',
    },
    {
        firstInterval: '10M',
        firstNote: 'E5',
        secondInterval: '11-',
        secondNote: 'Fb5',
    },
    {
        firstInterval: '11J',
        firstNote: 'F5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '11+',
        firstNote: 'F#5',
        secondInterval: '12-',
        secondNote: 'Gb5',
    },
    {
        firstInterval: '12J',
        firstNote: 'G5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '13m',
        firstNote: 'Ab5',
        secondInterval: '12+',
        secondNote: 'G#5',
    },
    {
        firstInterval: '13M',
        firstNote: 'A5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '14m',
        firstNote: 'Bb5',
        secondInterval: '13+',
        secondNote: 'A#5',
    },
    {
        firstInterval: '14M',
        firstNote: 'B5',
        secondInterval: '15-',
        secondNote: 'Cb6',
    },
    {
        firstInterval: '15J',
        firstNote: 'C6',
        secondInterval: '14+',
        secondNote: 'B#5',
    },
];

export const notesMenor = [
    {
        firstInterval: '1',
        firstNote: 'A2',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '2m',
        firstNote: 'Bb2',
        secondInterval: '1+',
        secondNote: 'A#2',
    },
    {
        firstInterval: '2M',
        firstNote: 'B2',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '3m',
        firstNote: 'C3',
        secondInterval: '2+',
        secondNote: 'B#2',
    },
    {
        firstInterval: '3M',
        firstNote: 'C#3',
        secondInterval: '4-',
        secondNote: 'Db3',
    },
    {
        firstInterval: '4J',
        firstNote: 'D3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '4+',
        firstNote: 'D#3',
        secondInterval: '5-',
        secondNote: 'Eb3',
    },
    {
        firstInterval: '5J',
        firstNote: 'E3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '6m',
        firstNote: 'F3',
        secondInterval: '5+',
        secondNote: 'E#3',
    },
    {
        firstInterval: '6M',
        firstNote: 'F#3',
        secondInterval: '7-',
        secondNote: 'Gb3',
    },
    {
        firstInterval: '7m',
        firstNote: 'G3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '7M',
        firstNote: 'G#3',
        secondInterval: '1-',
        secondNote: 'Ab3',
    },
    {
        firstInterval: '1',
        firstNote: 'A3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '2m',
        firstNote: 'Bb3',
        secondInterval: '1+',
        secondNote: 'A#3',
    },
    {
        firstInterval: '2M',
        firstNote: 'B3',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '3m',
        firstNote: 'C4',
        secondInterval: '2+',
        secondNote: 'B#3',
    },
    {
        firstInterval: '3M',
        firstNote: 'C#4',
        secondInterval: '4-',
        secondNote: 'Db4',
    },
    {
        firstInterval: '4J',
        firstNote: 'D4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '4+',
        firstNote: 'D#4',
        secondInterval: '5-',
        secondNote: 'Eb4',
    },
    {
        firstInterval: '5J',
        firstNote: 'E4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '6m',
        firstNote: 'F4',
        secondInterval: '5+',
        secondNote: 'E#4',
    },
    {
        firstInterval: '6M',
        firstNote: 'F#4',
        secondInterval: '7-',
        secondNote: 'Gb4',
    },
    {
        firstInterval: '7m',
        firstNote: 'G4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '7M',
        firstNote: 'G#4',
        secondInterval: '1-',
        secondNote: 'Ab4',
    },
    {
        firstInterval: '1',
        firstNote: 'A4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '9m',
        firstNote: 'Bb4',
        secondInterval: '9+',
        secondNote: 'A#4',
    },
    {
        firstInterval: '9M',
        firstNote: 'B4',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '10m',
        firstNote: 'C5',
        secondInterval: '10+',
        secondNote: 'B#5',
    },
    {
        firstInterval: '10M',
        firstNote: 'C#5',
        secondInterval: '11-',
        secondNote: 'Db5',
    },
    {
        firstInterval: '11J',
        firstNote: 'D5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '11+',
        firstNote: 'D#5',
        secondInterval: '12-',
        secondNote: 'Eb5',
    },
    {
        firstInterval: '12J',
        firstNote: 'E5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '13m',
        firstNote: 'F5',
        secondInterval: '13+',
        secondNote: 'E#5',
    },
    {
        firstInterval: '14m',
        firstNote: 'G5',
        secondInterval: '',
        secondNote: '',
    },
    {
        firstInterval: '14M',
        firstNote: 'G#5',
        secondInterval: '15-',
        secondNote: 'Ab5',
    },
    {
        firstInterval: '15J',
        firstNote: 'A5',
        secondInterval: '',
        secondNote: '',
    },
];
